# URL of video to play
url: ""
# screen size, in maps
size:
  width: 1
  height: 1
  # maximum width/height accepted internally (set to 0 or less to disable)
  cap: 10
# map ID offset
offset: 0
# sync interval, in seconds
interval: 10
# audio location
audio:
  x: 0
  y: 100
  z: 0
# image mode
image: false
# autoplay
autoplay: false